name: Build
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"
  pull_request:
    branches:
      - "**"


jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-22.04, ubuntu-20.04, windows-2019]
        node: [14, 16, 18]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install
        env:
          npm_config_build_from_source: true

      - name: Package prebuild
        run: yarn build

      - name: test
        run: yarn run test

  build_musl:
    name: Build (musl)
    runs-on: ubuntu-latest
    container:
      image: node:${{ matrix.node }}-alpine
    strategy:
      matrix:
        node: [14, 16, 18]
    steps:
      - name: Setup env with Node v${{ matrix.node }}
        run: |
          apk add --update
          apk add --no-cache ca-certificates git curl build-base python3 g++ make
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install
        env:
          npm_config_build_from_source: true

      - name: Package prebuild
        run: yarn build

      - name: test
        run: yarn run test