name: Prebuild(arm)
on:
  release:
    types: [published]

jobs:

  build_glibc:
    name: Prebuild (glibc)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
        node: [12, 14, 16, 17]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install
        env:
          npm_config_build_from_source: true

      - name: Package prebuild
        run: |
          sudo apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          rm openjtalk/mecab-naist-jdic/*.bin openjtalk/mecab-naist-jdic/*.dic
          cp prebuild/*/dictionary/* openjtalk/mecab-naist-jdic
          sed -i -e 's/"openjtalk\/mecab-naist-jdic\/build.gyp:\*",//g'  binding.gyp
          CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ yarn build-arm


      - name: Upload prebuild asset
        uses: icrawl/action-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: "build/stage/**/*.tar.gz"


  build_musl:
    name: Prebuild (musl)
    runs-on: ubuntu-latest
    container:
      image: node:${{ matrix.node }}-alpine
    strategy:
      fail-fast: false
      matrix:
        node: [12, 14, 16, 17]
    steps:
      - name: Setup env with Node v${{ matrix.node }}
        run: |
          apk add --update
          apk add --no-cache ca-certificates git curl build-base python3 g++ make

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup musl cross compiler
        run: |
          curl -OL https://musl.cc/aarch64-linux-musl-cross.tgz
          tar -xzvf aarch64-linux-musl-cross.tgz
          $(pwd)/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc --version

      - name: Install dependencies
        run: yarn install
        env:
          npm_config_build_from_source: true

      - name: Package prebuild
        run: |
          rm openjtalk/mecab-naist-jdic/*.bin openjtalk/mecab-naist-jdic/*.dic
          cp prebuild/*/dictionary/* openjtalk/mecab-naist-jdic
          sed -i -e 's/"openjtalk\/mecab-naist-jdic\/build.gyp:\*",//g'  binding.gyp
          CC=$(pwd)/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc \
          CXX=$(pwd)/aarch64-linux-musl-cross/bin/aarch64-linux-musl-g++ \
          yarn build-arm

      - name: Upload prebuild asset
        uses: icrawl/action-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: "build/stage/**/*.tar.gz"
