name: Prebuild(arm)
on:
  release:
    types: [published]

jobs:

  build_glibc:
    name: Prebuild (glibc)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
        node: [12, 14, 16, 17]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install
        env:
          npm_config_build_from_source: true

      - name: Package prebuild
        run: |
          sudo apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          rm openjtalk/mecab-naist-jdic/*.bin openjtalk/mecab-naist-jdic/*.dic
          cp prebuild/*/dictionary/* openjtalk/mecab-naist-jdic
          sed -i -e 's/"openjtalk\/mecab-naist-jdic\/build.gyp:\*",//g'  binding.gyp
          CC=gcc-aarch64-linux-gnu CXX=g++-aarch64-linux-gnu yarn build-arm


      - name: Upload prebuild asset
        uses: icrawl/action-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: "build/stage/**/*.tar.gz"

